services:
    database:
        image: mariadb:11.0.3
        ports:
          - "3306:3306"
        environment:
            MYSQL_USER:     "redmine"
            MYSQL_PASSWORD: "redmine"
            MYSQL_ROOT_PASSWORD: "redmine"
            MYSQL_DATABASE:      "redmine"
            TZ: "Asia/Tokyo"
        volumes:
          - "/var/lib/mysql:/var/lib/mysql"
          - "/var/lib/mysql/initdb.d:/docker-entrypoint-initdb.d"
        command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1"
        restart: always
        logging:
            driver: syslog
            options:
                syslog-address: "udp://127.0.0.1:514"
                tag: "reddb"

    redmine:
        image: redmine:5.1.2
        ports:
          - 80:3000
        depends_on:
          - database
        environment:
            TZ: "Asia/Tokyo"
            REDMINE_DB_MYSQL: "database"
            REDMINE_DB_PASSWORD: "redmine"
            REDMINE_SECRET_KEY_BASE: "supersecretkey"
        volumes:
          - "/var/lib/redmine:/usr/src/redmine/files"
        restart: always
        logging:
            driver: syslog
            options:
                syslog-address: "udp://127.0.0.1:514"
                tag: "redmine"

